function assprocessed = importfile1(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  ASSPROCESSED = IMPORTFILE1(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  ASSPROCESSED = IMPORTFILE1(FILE, SHEET) reads from the specified
%  worksheet.
%
%  ASSPROCESSED = IMPORTFILE1(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  assprocessed = importfile1("C:\Users\W20015790\OneDrive - Northumbria University - Production Azure AD\IS\ASSG\ass_processed.xlsx", "TrainingSet", [2, 38798]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-May-2022 11:42:00

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 38798];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 14);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":N" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["HeartDisease", "BMI", "Smoking", "AlcoholDrinking", "Stroke", "PhysicalHealth", "MentalHealth", "DiffWalking", "AgeCategory", "Diabetic", "PhysicalActivity", "GenHealth", "SleepTime", "Asthma"];
opts.VariableTypes = ["categorical", "double", "categorical", "categorical", "categorical", "double", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "double", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["HeartDisease", "Smoking", "AlcoholDrinking", "Stroke", "DiffWalking", "AgeCategory", "Diabetic", "PhysicalActivity", "GenHealth", "Asthma"], "EmptyFieldRule", "auto");

% Import the data
assprocessed = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":N" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    assprocessed = [assprocessed; tb]; %#ok<AGROW>
end

end